### ISSUE TITLE
Open source repository

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/emote#2]
Tracking issue to list what we want to do in this repo before making it public and open source.

Most is on https://github.com/EmbarkStudios/opensource/blob/main/content/how-to.md

- [x] Use the [Embark open source template](https://github.com/EmbarkStudios/opensource-template) and licenses
- [x] Make sure README is clear of intent and scope
- [x] Pick emoji to represent project, very important 😃
- [x] Add CODEOWNERS file that identifies who owns and maintains the repository, our bot verifies that all of our public projects have that

**Comment by tgolsson** [comment]
Closing this as we've been live and open for a long time now. If there are things we should work on let's open new issues that are clearer.
