### ISSUE TITLE
Bug at the dataloader

### ISSUE THREAD

**Issue by Ali-Ghadirzadeh** [EmbarkStudios/emote#73]
It seems there is a bug to load data during the training. It seems 'next_observation' is not constructed properly.

**Comment by tgolsson** [comment]
What's the exact bug? :-)

**Comment by Ali-Ghadirzadeh** [comment]
'next_observation' should be of the size [batch_size x observation_size]. However, it has much fewer (20x less) samples than batch_size

**Comment by tgolsson** [comment]
Is your rollout_length 20? It sounds like an nstep mismatch somewhere.

**Comment by Ali-Ghadirzadeh** [comment]
Thanks Tom! it is resolved.
