### ISSUE TITLE
DictGymWrapper - obs gets an empty extra dimension

### ISSUE THREAD

**Issue by Ali-Ghadirzadeh** [EmbarkStudios/emote#99]
In the DictGymWrapper class, the dict_reset method, the obs tensor gets an extra empty dimension. The obs tensor is produced by from self.reset_wait().

**Comment by tgolsson** [comment]
I have a faint memory of looking at this in another repository and it being caused by the vector-environments then. Might remember wrong... it's at least a year ago.

**Comment by Ali-Ghadirzadeh** [comment]
In newer gym versions, reset_wait in AsyncVectorEnv returns (obs, info), and info={} by default. So it is not a bug, but to prevent future issues, I'll update the code so that we first parse obs into obs and info, and use obs without using [0] index.
